### ISSUE TITLE
bbox_falloff - improve performance

### ISSUE THREAD

**Issue by akdbra** [kdbra/kdbra-houdini-tools#1]
It seems that something is working very slowly there
![image](https://user-images.githubusercontent.com/94026/109224873-96fb8880-77cd-11eb-8b84-b3afbc1901bf.png)

**Comment by nuclearpolygon** [comment]
Took a try. It have to be a bit faster now.

**Comment by nuclearpolygon** [comment]
![image](https://user-images.githubusercontent.com/45406953/109226983-a7613280-77d0-11eb-8442-b59454f95bbf.png)
it seems to got things even worse.

**Comment by nuclearpolygon** [comment]
note, this two ops themselves doesn't hurt performance at all. 
path in your screenshot just indicates the output of the object 
![image](https://user-images.githubusercontent.com/45406953/109227807-f65b9780-77d1-11eb-8f44-8c129312d18d.png)

the so I would better bring things back, this Copy trick doesn't seem to work.
